[package]

name = "math3d"
version = "0.0.1"
authors = ["Andrew Kelley <superjoe30@gmail.com>"]
license = "MIT"
description = "A simple rust library for computer-graphics matrix calculations."
repository = "https://github.com/andrewrk/math3d-rs"
